---
title: "Model Equations"
output:
  html_document: default
  pdf_document: default
date: '2022-05-03'
---
\[ER_t = AR_t + HR_{A,t} + HR_{D,t} + \epsilon_{obs,t}\]

#### Autotrophic Respiration  
\(AR_t = AR_f \times GPP_t\)  
  
\(AR_f = 0.44\)  

#### Latent Carbon Model:
\[HR_{D,t} = - K_t \times C_t\]
\[K_t = K_{20} \times e ^ {\frac{E_a}{k_b}(\frac{1}{T_t} - \frac{1}{293})}\] 
\[C_t = (C_{t-1}\times S_t + HR_{D,t} + L_t) \times \epsilon_{proc,t}\]
\[S_t = 1-0.8 \times \left( \frac{\tau(t) - \tau_0}{\tau_{max} - \tau_0} \right) ^2\]
\[\tau_t = \gamma_w \times r_t \times slope\]
\[\epsilon_{proc,t} \sim logNormal(0, \sigma_{proc})\]

Where allochthonous carbon inputs through litterfall $(L)$ are a fixed seasonal input to the system and the scour of detrital carbon $(S)$ is a function of the shear stress $(\tau)$ calculated using the speficic density of water $(\gamma_w)$, the hydraulic radius $(r)$ and the stream bed slope. 

#### Stochastic Antecedent Model:

\[HR_{A,t} = \beta_p \cdot \sum_{j=1}^N P_{ant,j}(t) * w_j\]
\[P_{ant,j}(t) = \sum_{\Delta t \in I_j}\frac{GPP(t-\Delta t)}{N(I_j)}\]
\[0 \leq w \leq 1, \sum_j w_j = 1\]

#### Observation model:

\[R_{obs}(t) \sim N(R(t), \sigma_{obs})\]

#### Priors on parameters

\(C_0 \sim \), The initial detrital C in the system
\(C_t \sim \), Detrital carbon at each timestep  
\(K_{20} \sim \), The carbon decay rate at 20 C  
\(\beta_s \sim \), The coefficient on scour as a function of shear stress  
\(\tau_0 \sim \), The minimum shear stress required for bed disturbance  
\(\beta_p \sim \), The coefficient on antecedent primary P  
\(\omega \sim dirichlet(1,1,...,1)\), Simplex coefficient on varying intervals of antecedent P  
\(\sigma_{proc} \sim\), Process error  
\(\sigma_{obs} \sim\), Observation error  


#### Constants

\(AR_f = 0.44\), The fraction of \(P\) that is respired by autotrophic respiration  
\(E_a = 0.63 eV\), The activation energy for carbon decay  
\(k_b = 8.6173 \cdot 10^{-5} eV/K\), Boltzmann's constant
